[database]
host = {{.Getenv "DB_HOST"}}
port = {{.Getenv "DB_PORT"}}
database = {{.Getenv "DB_NAME"}}
user = {{.Getenv "DB_USER"}}
password = {{.Getenv "DB_PASSWORD"}}
sslmode = {{.Getenv "DB_SSLMODE"}}
