// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: educations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEducation = `-- name: CreateEducation :one
INSERT INTO educations (resume_id, institution, degree, period, display_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resume_id, institution, degree, period, display_order
`

type CreateEducationParams struct {
	ResumeID     pgtype.UUID `json:"resume_id"`
	Institution  string      `json:"institution"`
	Degree       string      `json:"degree"`
	Period       string      `json:"period"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) CreateEducation(ctx context.Context, arg CreateEducationParams) (Education, error) {
	row := q.db.QueryRow(ctx, createEducation,
		arg.ResumeID,
		arg.Institution,
		arg.Degree,
		arg.Period,
		arg.DisplayOrder,
	)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.ResumeID,
		&i.Institution,
		&i.Degree,
		&i.Period,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteEducationsByResumeID = `-- name: DeleteEducationsByResumeID :exec
DELETE FROM educations WHERE resume_id = $1
`

func (q *Queries) DeleteEducationsByResumeID(ctx context.Context, resumeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEducationsByResumeID, resumeID)
	return err
}

const findEducationsByResumeID = `-- name: FindEducationsByResumeID :many
SELECT id, resume_id, institution, degree, period, display_order FROM educations WHERE resume_id = $1 ORDER BY display_order
`

func (q *Queries) FindEducationsByResumeID(ctx context.Context, resumeID pgtype.UUID) ([]Education, error) {
	rows, err := q.db.Query(ctx, findEducationsByResumeID, resumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Education{}
	for rows.Next() {
		var i Education
		if err := rows.Scan(
			&i.ID,
			&i.ResumeID,
			&i.Institution,
			&i.Degree,
			&i.Period,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
