// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experiences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExperience = `-- name: CreateExperience :one
INSERT INTO experiences (resume_id, company, role, period, description, display_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, resume_id, company, role, period, description, display_order
`

type CreateExperienceParams struct {
	ResumeID     pgtype.UUID `json:"resume_id"`
	Company      string      `json:"company"`
	Role         string      `json:"role"`
	Period       string      `json:"period"`
	Description  string      `json:"description"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, createExperience,
		arg.ResumeID,
		arg.Company,
		arg.Role,
		arg.Period,
		arg.Description,
		arg.DisplayOrder,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.ResumeID,
		&i.Company,
		&i.Role,
		&i.Period,
		&i.Description,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteExperiencesByResumeID = `-- name: DeleteExperiencesByResumeID :exec
DELETE FROM experiences WHERE resume_id = $1
`

func (q *Queries) DeleteExperiencesByResumeID(ctx context.Context, resumeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExperiencesByResumeID, resumeID)
	return err
}

const findExperiencesByResumeID = `-- name: FindExperiencesByResumeID :many
SELECT id, resume_id, company, role, period, description, display_order FROM experiences WHERE resume_id = $1 ORDER BY display_order
`

func (q *Queries) FindExperiencesByResumeID(ctx context.Context, resumeID pgtype.UUID) ([]Experience, error) {
	rows, err := q.db.Query(ctx, findExperiencesByResumeID, resumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Experience{}
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.ResumeID,
			&i.Company,
			&i.Role,
			&i.Period,
			&i.Description,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
