// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Education struct {
	ID           pgtype.UUID `json:"id"`
	ResumeID     pgtype.UUID `json:"resume_id"`
	Institution  string      `json:"institution"`
	Degree       string      `json:"degree"`
	Period       string      `json:"period"`
	DisplayOrder int32       `json:"display_order"`
}

type Experience struct {
	ID           pgtype.UUID `json:"id"`
	ResumeID     pgtype.UUID `json:"resume_id"`
	Company      string      `json:"company"`
	Role         string      `json:"role"`
	Period       string      `json:"period"`
	Description  string      `json:"description"`
	DisplayOrder int32       `json:"display_order"`
}

type Resume struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Title         string             `json:"title"`
	TemplateName  string             `json:"template_name"`
	PersonalName  string             `json:"personal_name"`
	PersonalTitle string             `json:"personal_title"`
	Email         string             `json:"email"`
	Phone         string             `json:"phone"`
	Location      string             `json:"location"`
	Summary       string             `json:"summary"`
	ShareToken    pgtype.Text        `json:"share_token"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	CsrfToken string             `json:"csrf_token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Skill struct {
	ID           pgtype.UUID `json:"id"`
	ResumeID     pgtype.UUID `json:"resume_id"`
	Name         string      `json:"name"`
	DisplayOrder int32       `json:"display_order"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Provider     string             `json:"provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
