// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resumes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResume = `-- name: CreateResume :one
INSERT INTO resumes (user_id, title, template_name, personal_name, personal_title, email, phone, location, summary, photo_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, title, template_name, personal_name, personal_title, email, phone, location, summary, photo_url, share_token, created_at, updated_at
`

type CreateResumeParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Title         string      `json:"title"`
	TemplateName  string      `json:"template_name"`
	PersonalName  string      `json:"personal_name"`
	PersonalTitle string      `json:"personal_title"`
	Email         string      `json:"email"`
	Phone         string      `json:"phone"`
	Location      string      `json:"location"`
	Summary       string      `json:"summary"`
	PhotoUrl      string      `json:"photo_url"`
}

func (q *Queries) CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error) {
	row := q.db.QueryRow(ctx, createResume,
		arg.UserID,
		arg.Title,
		arg.TemplateName,
		arg.PersonalName,
		arg.PersonalTitle,
		arg.Email,
		arg.Phone,
		arg.Location,
		arg.Summary,
		arg.PhotoUrl,
	)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.TemplateName,
		&i.PersonalName,
		&i.PersonalTitle,
		&i.Email,
		&i.Phone,
		&i.Location,
		&i.Summary,
		&i.PhotoUrl,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResume = `-- name: DeleteResume :exec
DELETE FROM resumes WHERE id = $1
`

func (q *Queries) DeleteResume(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResume, id)
	return err
}

const findResumeByID = `-- name: FindResumeByID :one
SELECT id, user_id, title, template_name, personal_name, personal_title, email, phone, location, summary, photo_url, share_token, created_at, updated_at FROM resumes WHERE id = $1
`

func (q *Queries) FindResumeByID(ctx context.Context, id pgtype.UUID) (Resume, error) {
	row := q.db.QueryRow(ctx, findResumeByID, id)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.TemplateName,
		&i.PersonalName,
		&i.PersonalTitle,
		&i.Email,
		&i.Phone,
		&i.Location,
		&i.Summary,
		&i.PhotoUrl,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findResumeByShareToken = `-- name: FindResumeByShareToken :one
SELECT id, user_id, title, template_name, personal_name, personal_title, email, phone, location, summary, photo_url, share_token, created_at, updated_at FROM resumes WHERE share_token = $1
`

func (q *Queries) FindResumeByShareToken(ctx context.Context, shareToken pgtype.Text) (Resume, error) {
	row := q.db.QueryRow(ctx, findResumeByShareToken, shareToken)
	var i Resume
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.TemplateName,
		&i.PersonalName,
		&i.PersonalTitle,
		&i.Email,
		&i.Phone,
		&i.Location,
		&i.Summary,
		&i.PhotoUrl,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findResumesByUserID = `-- name: FindResumesByUserID :many
SELECT id, user_id, title, template_name, personal_name, personal_title, email, phone, location, summary, photo_url, share_token, created_at, updated_at FROM resumes WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) FindResumesByUserID(ctx context.Context, userID pgtype.UUID) ([]Resume, error) {
	rows, err := q.db.Query(ctx, findResumesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resume{}
	for rows.Next() {
		var i Resume
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.TemplateName,
			&i.PersonalName,
			&i.PersonalTitle,
			&i.Email,
			&i.Phone,
			&i.Location,
			&i.Summary,
			&i.PhotoUrl,
			&i.ShareToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setShareToken = `-- name: SetShareToken :exec
UPDATE resumes SET share_token = $2 WHERE id = $1
`

type SetShareTokenParams struct {
	ID         pgtype.UUID `json:"id"`
	ShareToken pgtype.Text `json:"share_token"`
}

func (q *Queries) SetShareToken(ctx context.Context, arg SetShareTokenParams) error {
	_, err := q.db.Exec(ctx, setShareToken, arg.ID, arg.ShareToken)
	return err
}

const updatePhotoURL = `-- name: UpdatePhotoURL :exec
UPDATE resumes SET photo_url = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePhotoURLParams struct {
	ID       pgtype.UUID `json:"id"`
	PhotoUrl string      `json:"photo_url"`
}

func (q *Queries) UpdatePhotoURL(ctx context.Context, arg UpdatePhotoURLParams) error {
	_, err := q.db.Exec(ctx, updatePhotoURL, arg.ID, arg.PhotoUrl)
	return err
}

const updateResume = `-- name: UpdateResume :exec
UPDATE resumes SET title=$2, template_name=$3, personal_name=$4, personal_title=$5,
    email=$6, phone=$7, location=$8, summary=$9, photo_url=$10, updated_at=NOW()
WHERE id = $1
`

type UpdateResumeParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	TemplateName  string      `json:"template_name"`
	PersonalName  string      `json:"personal_name"`
	PersonalTitle string      `json:"personal_title"`
	Email         string      `json:"email"`
	Phone         string      `json:"phone"`
	Location      string      `json:"location"`
	Summary       string      `json:"summary"`
	PhotoUrl      string      `json:"photo_url"`
}

func (q *Queries) UpdateResume(ctx context.Context, arg UpdateResumeParams) error {
	_, err := q.db.Exec(ctx, updateResume,
		arg.ID,
		arg.Title,
		arg.TemplateName,
		arg.PersonalName,
		arg.PersonalTitle,
		arg.Email,
		arg.Phone,
		arg.Location,
		arg.Summary,
		arg.PhotoUrl,
	)
	return err
}
