// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (resume_id, name, display_order)
VALUES ($1, $2, $3)
RETURNING id, resume_id, name, display_order
`

type CreateSkillParams struct {
	ResumeID     pgtype.UUID `json:"resume_id"`
	Name         string      `json:"name"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, arg.ResumeID, arg.Name, arg.DisplayOrder)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ResumeID,
		&i.Name,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteSkillsByResumeID = `-- name: DeleteSkillsByResumeID :exec
DELETE FROM skills WHERE resume_id = $1
`

func (q *Queries) DeleteSkillsByResumeID(ctx context.Context, resumeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillsByResumeID, resumeID)
	return err
}

const findSkillsByResumeID = `-- name: FindSkillsByResumeID :many
SELECT id, resume_id, name, display_order FROM skills WHERE resume_id = $1 ORDER BY display_order
`

func (q *Queries) FindSkillsByResumeID(ctx context.Context, resumeID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, findSkillsByResumeID, resumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.ResumeID,
			&i.Name,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
